name: Item Report
description: Report an issue with a marketplace item.
title: "[Item Report] Insert marketplace item name here"
labels: ["item", "report"]
assignees:
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this item report!
  - type: textarea
    id: description 
    attributes:
      label: Description
      description: Describe the issue you are having with the marketplace item.
      placeholder: Describe the issue
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 7.0.0
        - 6.0.6
        - 6.0.5
        - 6.0.4
        - 6.0.3
        - 6.0.2
        - 6.0.1
        - 6.0.0
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Naver
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
